# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18a8b832f9a97d1c579f4aaa7100d7f678b8a91d96b3fe4b0ad313101a0318cfed73288817de0b09b2b4edda666aff68b39e0b692b363720e2a26e157fc2dfe2

test:
  secret_key_base: a4672bde49b30ccb7f23b30696ef189c98bff1884724cd79bc3c1263ded585428427d94579b1de3e526427fa6bf567b8c04040fd937886b57d7794db3ed018f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
